# Generated by Django 5.1 on 2024-08-15 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nashhappsapi', '0002_alter_event_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='spotify',
        ),
    ]
